# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c25f59ef12931aa3b4de4742f3858858ea52c0d64e4535e19d54408de4261e2c125f441694fbf39460cff1438c51b60ea3833dbd5ac6086b18c189b3917dbbd

test:
  secret_key_base: d5db167027bfc208f2a7f2472185af73a31f975e8599d3bec9cdd3e0b75fbdb563e2cd992b61d23d396908a5dad57e88ef9e3449671357ddac641db6832b48d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
